### ISSUE TITLE
Traceback (most recent call last): In main.py

### ISSUE THREAD

**Issue by ToxicSk1ll** [hxr404/Discord-ExpireBot#10]
Hello I get this error upon starting the bot:
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Discord-ExpireBot-main\bot\main.py", line 384, in <module>
    bot.run(os.environ.get('discord_token'))

**Comment by hxr404** [comment]
Sorry for the late reply.
Could you pls provide a screenshot of the error message / console Window

**Comment by ToxicSk1ll** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Desktop\Discord-ExpireBot-main\bot\main.py", line 384, in <module>
    bot.run(os.environ.get('discord_token'))
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by ToxicSk1ll** [comment]
Nevermind

**Comment by ToxicSk1ll** [comment]
My issue were the permissions that were mentioned in the error message. I wasnt able to read the message properly due to it disappearing quickly

**Comment by hxr404** [comment]
You forgot to enable the intents
Make Sure to enable both switches at https://discord.com/developers/applications/
![intents](https://user-images.githubusercontent.com/55095883/109213772-4bd37c80-77b1-11eb-9d63-9c8700cfd07c.png)

**Comment by ToxicSk1ll** [comment]
![image](https://user-images.githubusercontent.com/66040748/114435727-c838e800-9bc4-11eb-9ae0-7d96979912a7.png)

**Comment by hxr404** [comment]
you need to run the `addperm` command

**Comment by RichardJustine** [comment]
the 2nd reply of @hxr404 is helpful, thank you!
